resources:
  repositories:
    - repository: pipeline-template
      type: git
      name: "Study Definitions Repository/pipeline-template"


name: $(Build.DefinitionName)_$(SourceBranchName)_$(Build.BuildId)_$(Date:yyyyMMdd)

jobs:
  - template: angular-main.yml@pipeline-template
    parameters:
      run_ci: 'true'
      run_sonar: $(Sonar)